window.fbAsyncInit = ->
  FB.init
    appId: '1554515258198525'
    xfbml: true
    version: 'v2.5'
  return

((d, s, id) ->
  js = undefined
  fjs = d.getElementsByTagName(s)[0]
  if d.getElementById(id)
    return
  js = d.createElement(s)
  js.id = id
  js.src = '//connect.facebook.net/en_US/sdk.js'
  fjs.parentNode.insertBefore js, fjs
  return
) document, 'script', 'facebook-jssdk'

# ---
# generated by js2coffee 2.1.0
